version: '3.8'

services:
  run-api-locally:
    depends_on:
       - stud-active-api
    image: tianon/true
    restart: "no"

  stud-active-api:
      container_name: stud-active-api  
      build:
          context: .
      ports:
          - "7777:443"
      depends_on:
        - stud-active-db
  